### PR TITLE
fix: stop routing local MCP servers as remote publishers

### LINKED ISSUE #950: Orchestrator routes to local MCP server name as remote publisher, gets 404
## Bug Description

The orchestrator misroutes requests to a local MCP server name (playwright) as if it were a remote gateway publisher. The gateway returns HTTP 404 because no publisher with that slug exists.

User sees no response — the request silently fails after the orchestrator error.

## Reproduction

From Windows user log (tauri.localhost-1772567556529.log):

1. User has local MCP server playwright-stealth connected
2. User sends a prompt
3. Orchestrator classifies as code_generation / Moderate, decomposes into 1 subtask
4. Routes to McpPublisherWorker with publisher: playwright, model: google/gemini-3.1-pro-preview
5. Gateway returns 404: Publisher playwright not found
6. Repeats on every retry — user is stuck

## Log Evidence

```
[McpPublisherWorker] Executing with publisher: playwright, model: google/gemini-3.1-pro-preview
[McpPublisherWorker] HTTP 404 Not Found from publisher playwright
[Orchestrator] Worker error: Publisher returned HTTP 404 Not Found
```

This repeats 3 times in the log.

## Root Cause

The orchestrator classification/decomposition logic is confusing locally-connected MCP servers with remote gateway publishers. The local MCP server playwright-stealth should never appear as a publisher slug in McpPublisherWorker.

## Expected Behavior

- Local MCP servers should be excluded from publisher routing
- OR the orchestrator should distinguish between local MCP tools and remote publishers when decomposing subtasks

## Source

Windows user log from 2026-03-03.

### PR DESCRIPTION
**Pull request by taariq**
## Summary
- The orchestrator router checked for `mcp__` prefixed tools to decide publisher routing, but local MCP servers (e.g. `playwright-stealth`) also use the `mcp__` prefix
- This caused the router to extract `playwright` as a publisher slug and POST to `api.serendb.com/publishers/playwright/chat/completions`, which returned 404
- Users with any local MCP server connected were stuck with silent failures on every prompt
- Fix: `select_worker_type()` and `extract_publisher_slug()` now check for `gateway__` prefix (remote Seren publishers) instead of `mcp__` (local servers)
- Added regression test: `local_mcp_tools_do_not_trigger_publisher_routing`

## Test plan
- [x] All 39 router unit tests pass (including new regression test)
- [ ] With a local MCP server connected (e.g. playwright), send a Chat prompt — should route to ChatModel, not fail with 404
- [ ] With a gateway publisher tool available, send a prompt requiring tools — should still route to McpPublisher correctly

Closes #950

Taariq Lewis, SerenAI, Paloma, and Volume at https://serendb.com
Email: hello@serendb.com

### CODE REVIEW

File: src-tauri/src/orchestrator/router.rs [hunk 1]
```diff
@@ -82,12 +82,14 @@ fn select_worker_type(
         return WorkerType::AcpAgent;
     }
 
-    // Task requiring tools + publisher tools available → McpPublisher
+    // Task requiring tools + remote publisher tools available → McpPublisher
+    // Note: gateway__ = remote Seren publishers (Firecrawl, Perplexity, etc.)
+    //        mcp__    = local MCP servers (playwright-stealth, etc.) — NOT routable as publishers
     if classification.requires_tools
```
Comment (taariq) [inline src-tauri/src/orchestrator/router.rs]: This condition now captures **all** `requires_tools=true` tasks when any `gateway__` tool exists. That includes `code_generation` and `file_operations` (classifier sets `requires_tools=true` for both), so users without an active ACP session will be routed to `McpPublisher` instead of `ChatModel`.

Repro from current code paths:
- `task_type = "code_generation"`, `requires_file_system = true`, `has_acp_agent = false`
- `available_tools` contains `gateway__firecrawl-serenai__scrape` (common after gateway init)
- router returns `WorkerType::McpPublisher`

That sends coding/file tasks to `/publishers/{slug}/chat/completions`, which cannot satisfy local file-operation flows and is a behavioral regression. We should gate publisher routing by task intent (e.g. research/publisher-only), or at minimum exclude file-system tasks.

File: src-tauri/src/orchestrator/router.rs [hunk 2]
```diff
@@ -112,7 +114,7 @@ fn extract_publisher_slug(
         .available_tools
         .iter()
         .filter_map(|t| {
-            let rest = t.strip_prefix("mcp__")?;
+            let rest = t.strip_prefix("gateway__")?;
```
Comment (taariq) [inline src-tauri/src/orchestrator/router.rs]: Selecting the publisher by taking the first matching tool here is unsafe with multi-publisher toolsets. The chosen slug depends on `available_tools` order rather than task intent.

With active tools like `gateway__google-calendar__...` and `gateway__firecrawl-serenai__...`, this can route a research prompt to the wrong publisher endpoint.

Given the new `gateway__` worker-selection logic, this ambiguity is now on the hot path. We should select by explicit intent/skill, or require a single eligible publisher before choosing `McpPublisher`.
